# Generated by Django 3.1.2 on 2020-11-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.IntegerField()),
                ('rut', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=40)),
                ('f_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=35)),
                ('c_residencia', models.CharField(max_length=40)),
                ('c_trabajo', models.CharField(max_length=40)),
            ],
        ),
    ]
