# Generated by Django 3.1.2 on 2020-11-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docente',
            new_name='Funcionario',
        ),
    ]
